[package]
name = "observer_ward"
version = "0.1.0"
authors = ["Kali-Team <root@kali-team.cn>"]
edition = "2018"
description = "Identifies technologies used on a web page."
license = "MIT"
include = ["LICENSE", "Cargo.toml", "src/**/*.rs"]
[workspace]
members = [".", "nuclei_rs", "target_input"]
[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
[profile.release.package.nuclei_rs]
opt-level = "z"
codegen-units = 1
[features]
nuclei_rs = ["observer_ward_nuclei_rs"]
[dependencies]
walkdir = "2"
cached = "0.26.2"
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
serde_derive = "1.0"
reqwest = { version = "0.11.6", features = ["socks", "blocking", "gzip", "cookies"] }
tokio = { version = "1.14.0", features = ["full"] }
futures = { version = "0.3", features = ["compat"] }
url = { version = "2.1.1", features = ["serde"] }
scraper = "0.10.1"
hex-literal = "0.3.3"
lazy_static = "1.4.0"
clap = "2.33.3"
term = "*"
prettytable-rs = "^0.8"
textwrap = "0.14"
log = "0.4.0"
encoding_rs = "0.8.28"
regex = { version = "1.4.5", default-features = false, features = ["std", "unicode"] }
mime = "0.3.16"
md-5 = "0.9.1"
base64 = "0.13.0"
csv = "1.1.6"
observer_ward_nuclei_rs = { path = "nuclei_rs", optional = true, default-features = false, package = "nuclei_rs" }
observer_ward_target_input = { path = "target_input", package = "target_input" }
[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1"

[patch.crates-io]
# REDOX START, Uncommment when you want to compile/check with redoxer
# REDOX END
[profile.dev.package."*"]
opt-level = 3
[profile.test]
opt-level = 3
lto = "thin"

[profile.bench]
lto = true
codegen-units = 1
opt-level = 3