[package]
name = "what_web"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
encoding_rs = "0.8.28"
regex = { version = "1.4.5", default-features = false, features = ["std", "unicode"] }
mime = "0.3.16"
md-5 = "0.9.1"
base64 = "0.13.0"
cached = "0.26.2"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
serde_derive = "1.0"
reqwest = { version = "0.11.6", default-features = false, features = ["rustls-tls", "socks", "blocking", "gzip", "cookies", "json"] }
futures = { version = "0.3", features = ["compat"] }
url = { version = "2.1.1", features = ["serde"] }
tokio = { version = "1.14.0", features = ["full"] }