name: Rust

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          default: true
          override: true

      - name: Build
        run: |
          sudo apt-get install upx-ucl -y
          sudo apt-get install musl-tools -y
          sudo apt-get install pkg-config libssl-dev -y
          cargo build --target=x86_64-unknown-linux-musl --release --all-features
          strip target/x86_64-unknown-linux-musl/release/observer_ward
          upx --best --lzma target/x86_64-unknown-linux-musl/release/observer_ward
          mv target/x86_64-unknown-linux-musl/release/observer_ward target/x86_64-unknown-linux-musl/release/observer_ward_amd64

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-musl/release/observer_ward_amd64
          asset_name: observer_ward_amd64
          tag: default
          overwrite: true

  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: target/release/observer_ward.exe
          strip: false
          args: -9
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/observer_ward.exe
          asset_name: observer_ward.exe
          tag: default
          overwrite: true

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true
      - name: Build for mac
        run: |
          cargo build --target=x86_64-apple-darwin --release --all-features
          strip target/x86_64-apple-darwin/release/observer_ward
          mv target/x86_64-apple-darwin/release/observer_ward target/x86_64-apple-darwin/release/observer_ward_darwin
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-apple-darwin/release/observer_ward_darwin
          asset_name: observer_ward_darwin
          tag: default
          overwrite: true