[package]
name = "observer_ward"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine = { path = "../engine" }
argh = "0.1.12"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1"
dirs = "5.0.1"
threadpool = "1.8.1"
thiserror = "1"
env_logger = { version = "0.11.3", default-features = false, features = [
  "auto-color",
] }
log = "0.4.21"
console = "0.15.8"
rustc_lexer = "0.1.0"
zip = { version = "2.1.3", default-features = false, features = ["deflate"] }
actix-web-httpauth = "0.8.1"
actix-web = { version = "4.6.0", default-features = false, features = ["macros", "compress-gzip", "openssl"] }
[target.'cfg(target_os="windows")'.build-dependencies]
winres = "0.1"
[target.'cfg(not(target_os = "windows"))'.dependencies]
daemonize = "0.5.0"